---
- hosts: all
  become: yes
  gather_facts: no
  vars:
    image: maur1th/attendees
    app_port: 3000
    db_name: attendeelist
    db_user: admin
    db_password: devops2017

  roles:
  - common
  - docker
  - nginx
  - app
...
